apiVersion: v2
name: k8s-aws-ebs-tagger
description: An app to tag AWS EBS volumes based on a PVC annotation
home: https://github.com/mtougeron/k8s-aws-ebs-tagger
type: application
maintainers:
  - name: mtougeron
    email: github@e.tougeron.com
keywords:
  - kubernetes
  - aws
  - aws-ebs
sources:
  - https://github.com/mtougeron/k8s-aws-ebs-tagger

version: 1.1.1
appVersion: v0.0.2
